##### TABLES #####

# surv_jobss.geo_images_footprint --------------------------------------------------------------------------------
#' Get JoBSS data: geo_images_footprint
#'
#' @description
#' Return all records from surv_jobss.geo_images_footprint as an sp object
#'
#' @details
#' This function returns all records in the surv_jobss.geo_images_footprint table. This table contains all the spatial footprints for the IR, RGB and UV images
#' that were collected during the 2021 JoBSS aerial survey flights. These footprints were generated by the post-processing script developed by Kitware as part of the KAMERA system.
#'
#' The code used to import these data into the database can be found in the
#' \href{https://github.com/StacieKozHardy/IceSeal_JoBSS_DataManagement}{IceSeal_JoBSS_DataManagement} repository on GitHub.
#'
#' The data in this table relate to other JoBSS data based on the following fields:
#' \itemize{
#'   \item flight, camera_view, dt
#'   \item image_name
#' }
#'
#' @param con A connection string to the PEP PostgreSQL database
#'
#' @return A sp object containing all records in the surv_jobss.geo_images_footprint table.
#' @export
#'
#' @examples
#' # Connect to PEP database
#' con <- pep_connect()
#'
#' # Get data and do a lot of cool stuff here
#' data <- surv_jobss.geo_images_footprint(con)
#'
#' # When you're done, disconnect from the database
#' pep_disconnect(con)
#'
surv_jobss.geo_images_footprint <- function(con){
  sf::st_read(con, query = "SELECT * FROM surv_jobss.geo_images_footprint")
}


# surv_jobss.geo_images_meta --------------------------------------------------------------------------------
#' Get JoBSS data: geo_images_meta
#'
#' @description
#' Return all records from surv_jobss.geo_images_meta as an sp object
#'
#' @details
#' This function returns all records in the surv_jobss.geo_images_meta table. This table contains all the data in each of the meta.json files associated with set of IR, RGB, and UV images that were collected
#' during the 2021 JoBSS aerial survey flights using the KAMERA system developed by Kitware.  The data are largely an output of information from the INS. The locations are created based on the coordinates
#' recorded to the INS, and these locations are reflect the location of the aircraft(not the location of the image or its footprint) at the time the image was taken.
#' All left and right camera view locations should match that of the center camera view in this data set. The code used to import these data into the database can be found in the
#' \href{https://github.com/StacieKozHardy/IceSeal_JoBSS_DataManagement}{IceSeal_JoBSS_DataManagement} repository on GitHub.
#'
#' The effort_reconciled field was generated and updated post-survey to reflect any necessary changes to the field-recorded effort values. The code associated with these changes can be found in the
#' \href{https://github.com/StacieKozHardy/IceSeal_JoBSS_DataManagement}{IceSeal_JoBSS_DataManagement} repository on GitHub.
#'
#' The data in this table relate to other JoBSS data based on the following fields:
#' \itemize{
#'   \item flight, camera_view, dt
#'   \item image_group (for joining these data more easily to the data stored in sub_jobss.tbl_images)
#' }
#'
#' @param con A connection string to the PEP PostgreSQL database
#'
#' @return A sp object containing all records in the surv_jobss.geo_images_meta table.
#' @export
#'
#' @examples
#' # Connect to PEP database
#' con <- pep_connect()
#'
#' # Get data and do a lot of cool stuff here
#' data <- surv_jobss.geo_images_meta(con)
#'
#' # When you're done, disconnect from the database
#' pep_disconnect(con)
#'
surv_jobss.geo_images_meta <- function(con){
  sf::st_read(con, query = "SELECT * FROM surv_jobss.geo_images_meta")
}


# surv_jobss.tbl_detections_original_ir --------------------------------------------------------------------------------
#' Get JoBSS data: tbl_detections_original_ir
#'
#' @description
#' Return all records from surv_jobss.tbl_detections_original_ir as a data frame
#'
#' @details
#' This function returns all records in the surv_jobss.tbl_detections_original_ir table. This table contains all the \emph{original} detection outputs from the ice seal ir-rgb trigger detection model
#' associated with the IR images. This table reflects the original, unreviewed detections.
#'
#' The detection_id field was created to have a unique identifier assigned to all detections as they related to one another across all detection tables, with the exception of the original_rgb table.
#' The records in the original_rgb table are different and cannot be linked to the rest of the data without using the surv_jobss.tbl_detections_original2processed_rgb table.
#' \strong{NOTE}: any records that do not exist in original IR table but exist in any of the processed tables were found and added to the dataset during the review process.
#'
#' The code used to import these data into the database can be found in the
#' \href{https://github.com/StacieKozHardy/IceSeal_JoBSS_DataManagement}{IceSeal_JoBSS_DataManagement} repository on GitHub.
#'
#' The data in this table relate to other JoBSS data based on the following fields:
#' \itemize{
#'   \item image_name
#'   \item detection_id
#' }
#'
#' @param con A connection string to the PEP PostgreSQL database
#'
#' @return A data frame object containing all records in the surv_jobss.tbl_detections_original_ir table.
#' @export
#'
#' @examples
#' # Connect to PEP database
#' con <- pep_connect()
#'
#' # Get data and do a lot of cool stuff here
#' data <- surv_jobss.tbl_detections_original_ir(con)
#'
#' # When you're done, disconnect from the database
#' pep_disconnect(con)
#'
surv_jobss.tbl_detections_original_ir <- function(con){
  RPostgreSQL::dbGetQuery(con, "SELECT * FROM surv_jobss.tbl_detections_original_ir")
}

# surv_jobss.tbl_detections_original_rgb --------------------------------------------------------------------------------
#' Get JoBSS data: tbl_detections_original_rgb
#'
#' @description
#' Return all records from surv_jobss.tbl_detections_original_rgb as a data frame
#'
#' @details
#' This function returns all records in the surv_jobss.tbl_detections_original_rgb table. This table contains all the \emph{original} detection outputs from the ice seal ir-rgb trigger detection model
#' associated with the RGB images. This table reflects the original, unreviewed detections.
#'
#' The detection_id field was created to have a unique identifier assigned to all detections as they related to one another across all detection tables, with the exception of the original_rgb table.
#' The records in the original_rgb table are different and cannot be linked to the rest of the data without using the surv_jobss.tbl_detections_original2processed_rgb table. Details about how to link
#' these data can be found in the documentation for the surv_jobss.tbl_detections_original2processed_rgb function.
#'
#' The code used to import these data into the database can be found in the
#' \href{https://github.com/StacieKozHardy/IceSeal_JoBSS_DataManagement}{IceSeal_JoBSS_DataManagement} repository on GitHub.
#'
#' The data in this table relate to other JoBSS data based on the following fields:
#' \itemize{
#'   \item image_name
#'   \item id
#' }
#'
#' @param con A connection string to the PEP PostgreSQL database
#'
#' @return A data frame object containing all records in the surv_jobss.tbl_detections_original_rgb table.
#' @export
#'
#' @examples
#' # Connect to PEP database
#' con <- pep_connect()
#'
#' # Get data and do a lot of cool stuff here
#' data <- surv_jobss.tbl_detections_original_rgb(con)
#'
#' # When you're done, disconnect from the database
#' pep_disconnect(con)
#'
#' @seealso
#' \code{\link{surv_jobss.tbl_detections_original2processed_rgb}}
#'
surv_jobss.tbl_detections_original_rgb <- function(con){
  RPostgreSQL::dbGetQuery(con, "SELECT * FROM surv_jobss.tbl_detections_original_rgb")
}

# surv_jobss.tbl_detections_original2processed_rgb --------------------------------------------------------------------------------
#' Get JoBSS data: tbl_detections_original2processed_rgb
#'
#' @description
#' Return all records from surv_jobss.tbl_detections_original2processed_rgb as a data frame
#'
#' @details
#' This function returns all records in the surv_jobss.tbl_detections_original2processed_rgb table. This table contains the links between the original RGB detections (which have a different unique identifier)
#' to the processed RGB detections. These links are made based on the id fields in the surv_jobss.tbl_detections_original_rgb and surv_jobss.tbl_detections_processed_rgb tables via this table. The processed RGB
#' detections can be linked to the original RGB detections based on two methods: closest bounding box or highest score. You will need to choose \emph{one} of these methods for joining the data.
#'
#' The code used to generate these matches can be found in the
#' \href{https://github.com/StacieKozHardy/IceSeal_JoBSS_DataManagement}{IceSeal_JoBSS_DataManagement} repository on GitHub.
#'
#' The data in this table relate to other JoBSS data based on the following fields:
#' \itemize{
#'   \item image_name
#'   \item processed_id (for joining records to the id field in surv_jobss.tbl_detections_processed_rgb)
#'   \item original_id_distance (for joining records to the id field in surv_jobss.tbl_detections_original_rgb, where the processed RGB detection best matched based on bounding box distance)
#'   \item original_id_score (for joining records to the id field in surv_jobss.tbl_detections_original_rgb, where the processed RGB detection best matched based on highest detection score)
#' }
#'
#' @param con A connection string to the PEP PostgreSQL database
#'
#' @return A data frame object containing all records in the surv_jobss.tbl_detections_original2processed_rgb table.
#' @export
#'
#' @examples
#' # Connect to PEP database
#' con <- pep_connect()
#'
#' # Get data and do a lot of cool stuff here
#' data <- surv_jobss.tbl_detections_original2processed_rgb(con)
#'
#' # When you're done, disconnect from the database
#' pep_disconnect(con)
#'
#' @seealso
#' \code{\link{surv_jobss.tbl_detections_original_rgb}}
#' \code{\link{surv_jobss.tbl_detections_processed_rgb}}
#'
surv_jobss.tbl_detections_original2processed_rgb <- function(con){
  RPostgreSQL::dbGetQuery(con, "SELECT * FROM surv_jobss.tbl_detections_original2processed_rgb")
}



# surv_jobss.tbl_detections_processed_ir --------------------------------------------------------------------------------
#' Get JoBSS data: tbl_detections_processed_ir
#'
#' @description
#' Return all records from surv_jobss.tbl_detections_processed_ir as a data frame
#'
#' @details
#' This function returns all records in the surv_jobss.tbl_detections_processed_ir table. This table contains all the \emph{processed} detection outputs from the ice seal ir-rgb trigger detection model
#' associated with the IR images. This table reflects the reviewed detections, where original detections have been changed to their correct assignments based on a review.
#'
#' The detection_id field was created to have a unique identifier assigned to all detections as they related to one another across all detection tables, with the exception of the original_rgb table.
#' The records in the original_rgb table are different and cannot be linked to the rest of the data without using the surv_jobss.tbl_detections_original2processed_rgb table.
#' \strong{NOTE}: any records that do not exist in original IR table but exist in any of the processed tables were found and added to the dataset during the review process.
#'
#' The code used to import these data into the database can be found in the
#' \href{https://github.com/StacieKozHardy/IceSeal_JoBSS_DataManagement}{IceSeal_JoBSS_DataManagement} repository on GitHub.
#'
#' The data in this table relate to other JoBSS data based on the following fields:
#' \itemize{
#'   \item image_name
#'   \item detection_id
#' }
#'
#' @param con A connection string to the PEP PostgreSQL database
#'
#' @return A data frame object containing all records in the surv_jobss.tbl_detections_processed_ir table.
#' @export
#'
#' @examples
#' # Connect to PEP database
#' con <- pep_connect()
#'
#' # Get data and do a lot of cool stuff here
#' data <- surv_jobss.tbl_detections_processed_ir(con)
#'
#' # When you're done, disconnect from the database
#' pep_disconnect(con)
#'
surv_jobss.tbl_detections_processed_ir <- function(con){
  RPostgreSQL::dbGetQuery(con, "SELECT * FROM surv_jobss.tbl_detections_processed_ir")
}


# surv_jobss.tbl_detections_processed_rgb --------------------------------------------------------------------------------
#' Get JoBSS data: tbl_detections_processed_rgb
#'
#' @description
#' Return all records from surv_jobss.tbl_detections_processed_rgb as a data frame
#'
#' @details
#' This function returns all records in the surv_jobss.tbl_detections_processed_rgb table. This table contains all the \emph{processed} detection outputs from the ice seal ir-rgb trigger detection model
#' associated with the IR images, which were transposed to the RGB images (using the appropriate transformation file) and were reviewed for species ID.
#'
#' The detection_id field was created to have a unique identifier assigned to all detections as they related to one another across all detection tables, with the exception of the original_rgb table.
#' The records in the original_rgb table are different and cannot be linked to the rest of the data without using the surv_jobss.tbl_detections_original2processed_rgb table.
#' \strong{NOTE}: any records that do not exist in original IR table but exist in any of the processed tables were found and added to the dataset during the review process.
#'
#' The code used to import these data into the database can be found in the
#' \href{https://github.com/StacieKozHardy/IceSeal_JoBSS_DataManagement}{IceSeal_JoBSS_DataManagement} repository on GitHub.
#'
#' The data in this table relate to other JoBSS data based on the following fields:
#' \itemize{
#'   \item image_name
#'   \item detection_id
#' }
#'
#' @param con A connection string to the PEP PostgreSQL database
#'
#' @return A data frame object containing all records in the surv_jobss.tbl_detections_processed_rgb table.
#' @export
#'
#' @examples
#' # Connect to PEP database
#' con <- pep_connect()
#'
#' # Get data and do a lot of cool stuff here
#' data <- surv_jobss.tbl_detections_processed_rgb(con)
#'
#' # When you're done, disconnect from the database
#' pep_disconnect(con)
#'
#' @seealso
#' \code{\link{surv_jobss.tbl_detections_original2processed_rgb}}
#'
surv_jobss.tbl_detections_processed_rgb <- function(con){
  RPostgreSQL::dbGetQuery(con, "SELECT * FROM surv_jobss.tbl_detections_processed_rgb")
}


# surv_jobss.tbl_images --------------------------------------------------------------------------------
#' Get JoBSS data: tbl_images
#'
#' @description
#' Return all records from surv_jobss.tbl_images as a data frame
#'
#' @details
#' This function returns all records in the surv_jobss.geo_images_meta table. This table contains an inventory of all the IR, RGB, and UV images that were collected
#' during the 2021 JoBSS aerial survey flights using the KAMERA system developed by Kitware. The following fields supplement the list of images:
#' \itemize{
#'   \item image_type - indicates if the image is ir_image, rgb_image or uv_image
#'   \item image_dir - provides the network path to the image; useful for copying images or ad hoc generating image lists
#'   \item ir_nuc - the authoritative field for designating if the IR image at that timestamp was NUC
#'   \item rgb_manualreview - indicates if the RGB image at that timestamp was selected for manual review
#'   \item ir_nuc_rf_mlp - indicates if the IR image at that timestamp was NUC based on the random forest and a multilayer-perceptron classifier method
#'   \item ir_nuc_svm - indicates if the IR image at that timestamp was NUC based on the SVM machine learning algorithm method
#'   \item image_group - a unique identifier that clusters the IR, RGB and UV images for a particular flight, camera view and date/time together;
#'   was created for joining these data more easily to the data stored in sub_jobss.geo_images_meta
#'   \item  ir_nuc_review - indicates if the IR image was selected for a manual review of IR NUC events for validating the two approaches
#' }
#'
#' The code used to import these data into the database and process them once they were imported can be found in the
#' \href{https://github.com/StacieKozHardy/IceSeal_JoBSS_DataManagement}{IceSeal_JoBSS_DataManagement} repository on GitHub.
#'
#' The data in this table relate to other JoBSS data based on the following fields:
#' \itemize{
#'   \item flight, camera_view, dt
#'   \item image_name
#'   \item image_group (for joining these data more easily to the data stored in sub_jobss.geo_images_meta)
#' }
#'
#' @param con A connection string to the PEP PostgreSQL database
#'
#' @return A data frame object containing all records in the surv_jobss.tbl_images table.
#' @export
#'
#' @examples
#' # Connect to PEP database
#' con <- pep_connect()
#'
#' # Get data and do a lot of cool stuff here
#' data <- surv_jobss.tbl_images(con)
#'
#' # When you're done, disconnect from the database
#' pep_disconnect(con)
#'
surv_jobss.tbl_images <- function(con){
  RPostgreSQL::dbGetQuery(con, "SELECT * FROM surv_jobss.tbl_images")
}

##### QUERIES #####

# surv_jobss.geo_4abundance_images --------------------------------------------------------------------------------
#' Get JoBSS data: geo_4abundance_images
#'
#' @description
#' Return all records from surv_jobss.geo_4abundance_images as an sp object
#'
#' @details
#' This function returns the selected records from a query that was developed a stand-alone product for the Beaufort Sea ice seal abundance estimates.
#' The spatial data in this query reflect the area of survey effort during the 2021 JoBSS aerial survey flights.
#'
#' The data in this query relate to other JoBSS data based on the following fields:
#' \itemize{
#'   \item flight, camera_view, dt
#'   \item image_name
#' }
#'
#' @param con A connection string to the PEP PostgreSQL database
#'
#' @return A sp object containing all records in the surv_jobss.geo_4abundance_images query.
#' @export
#'
#' @examples
#' # Connect to PEP database
#' con <- pep_connect()
#'
#' # Get data and do a lot of cool stuff here
#' data <- surv_jobss.geo_4abundance_images(con)
#'
#' # When you're done, disconnect from the database
#' pep_disconnect(con)

#'
surv_jobss.geo_4abundance_images <- function(con){
  sf::st_read(con, query = "SELECT * FROM surv_jobss.geo_4abundance_images")
}

# surv_jobss.geo_4abundance_seals --------------------------------------------------------------------------------
#' Get JoBSS data: geo_4abundance_seals
#'
#' @description
#' Return all records from surv_jobss.geo_4abundance_seals as an sp object
#'
#' @details
#' This function returns the selected records from a query that was developed a stand-alone product for the Beaufort Sea ice seal abundance estimates.
#' The spatial data in this query reflect the midpoints of frames in which on-effort ice seals were detected by the IR model from images collected during the 2021 JoBSS aerial survey flights.
#'
#' The data in this query relate to other JoBSS data based on the following fields:
#' \itemize{
#'   \item flight, camera_view, dt
#'   \item image_name
#'   \item detection_id
#' }
#'
#' @param con A connection string to the PEP PostgreSQL database
#'
#' @return A sp object containing all records in the surv_jobss.geo_4abundance_seals query.
#' @export
#'
#' @examples
#' # Connect to PEP database
#' con <- pep_connect()
#'
#' # Get data and do a lot of cool stuff here
#' data <- surv_jobss.geo_4abundance_seals(con)
#'
#' # When you're done, disconnect from the database
#' pep_disconnect(con)
#'
surv_jobss.geo_4abundance_seals <- function(con){
  sf::st_read(con, query = "SELECT * FROM surv_jobss.geo_4abundance_seals")
}
